### ISSUE TITLE
'utf-8' codec can't decode byte 0xdc in position 11: unexpected end of data

### ISSUE THREAD

**Issue by KRaudla** [RRisto/ettvotted#6]
Traceback (most recent call last):
  File "C:/Users/kasutaja/Documents/GitHub/ettvotted.git/geocode.py", line 8, in <module>
    data = pandas.read_csv('list.csv',sep=";",encoding="utf-8")
  File "C:\Users\kasutaja\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 491, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\kasutaja\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 278, in _read
    return parser.read()
  File "C:\Users\kasutaja\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 740, in read
    ret = self._engine.read(nrows)
  File "C:\Users\kasutaja\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1187, in read
    data = self._reader.read(nrows)
  File "pandas\parser.pyx", line 758, in pandas.parser.TextReader.read (pandas\parser.c:7919)
  File "pandas\parser.pyx", line 780, in pandas.parser.TextReader._read_low_memory (pandas\parser.c:8175)
  File "pandas\parser.pyx", line 855, in pandas.parser.TextReader._read_rows (pandas\parser.c:9126)
  File "pandas\parser.pyx", line 962, in pandas.parser.TextReader._convert_column_data (pandas\parser.c:10519)
  File "pandas\parser.pyx", line 1022, in pandas.parser.TextReader._convert_tokens (pandas\parser.c:11405)
  File "pandas\parser.pyx", line 1120, in pandas.parser.TextReader._convert_with_dtype (pandas\parser.c:13003)
  File "pandas\parser.pyx", line 1133, in pandas.parser.TextReader._string_convert (pandas\parser.c:13184)
  File "pandas\parser.pyx", line 1372, in pandas.parser._string_box_utf8 (pandas\parser.c:18799)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 11: unexpected end of data

**Comment by RRisto** [comment]
mingi kodeeringu jama tundub olevat. andis selle teate kohe alguses?

**Comment by KRaudla** [comment]
encoding="latin-1" did the trick.

Teine hoiatus tekkis. sys:1: DtypeWarning: Columns (15,16) have mixed types. Specify dtype option on import or set low_memory=False.

Kuid kood töötab.

**Comment by RRisto** [comment]
pean proovima, kas seda latin-1 on ikka vaja

**Comment by RRisto** [comment]
kui ma latin-1 maha võtan, siis annab errori: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 11: unexpected end of dat kuskil on mingi erinevus sees siis meie pythonis/arvutis.
